name: flutter_news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # state management to manage the state
  flutter_bloc: ^8.1.3
  # comparing objects
  equatable: ^2.0.5
  # dependency injection
  get_it: ^7.6.0
  # format datetime
  intl: ^0.18.1
  # to persist the data in local storage 
  floor: ^1.4.2
  # 
  flutter_hooks: ^0.20.0
  # api calls
  retrofit: ^4.0.1
  dio: ^5.3.2
  # to cache the network images
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.8.4
  connectivity_plus: ^4.0.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # generators to automatically generate the code for you
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Light.ttf
          weight: 300
